---
# tridentctl depends on kubectl and kubeconfig
- name: check for kubectl
  stat:
    path: "/usr/local/bin/kubectl"
  register: kubectl_system
  delegate_to: localhost
  run_once: true

- include: kubectl.yml
  when: kubectl_system.stat.exists|default(false) | bool == false

# install the tridentctl client
- name: Download and extract Trident installer
  unarchive:
    src: '{{ trident_installer_url }}'
    dest: '{{ artifacts_dir }}'
    remote_src: yes
  delegate_to: localhost
  run_once: true

- name: copy tridentctl to /usr/local/bin
  copy:
    src: "{{ artifacts_dir }}/tridentctl"
    dest: "/usr/local/bin/tridentctl"
  when: tridentctl_local.stat.exists
  become: yes
  ignore_errors: yes
  register: tridentctl_copied
  delegate_to: localhost
  run_once: true

- name: check for copied tridentctl
  stat:
    path: "/usr/local/bin/tridentctl"
  register: tridentctl_system
  delegate_to: localhost
  run_once: true

- name: modify tridentctl permissions
  file:
    path: "/usr/local/bin/tridentctl"
    owner: root
    group: root
    mode: '0755'
  become: yes
  ignore_errors: yes
  when: tridentctl_system.stat.exists
  delegate_to: localhost
  run_once: true

- name: manually move tridentctl binary
  debug:
    msg: "Unable to move tridentctl, run: sudo cp {{ artifacts_dir | realpath }}/tridentctl /usr/local/bin"
  when: tridentctl_copied is failed
  delegate_to: localhost
  run_once: true

# copy from localhost to kube-masters - Not sure this is necessary
# - name: Copy tridentctl to the k8s control nodes
#   ansible.builtin.copy:
#     src: /usr/local/bin/tridentctl
#     dest: /usr/local/bin/tridentctl
#     owner: root
#     group: root
#     mode: '0755'
#   when: tridentctl_system.stat.exists and copy_tridentctl_to_kube_master
#   run_once: false
