---
# Playbook for deploying NetApp Trident

- name: "Install NFS utils on worker nodes"
  hosts: kube-node
  become: true
  become_method: sudo
  tasks:
  - name: install nfs utils (Ubuntu)
    package:
      name: nfs-common
    when: ansible_os_family == "Debian"
  - name: install nfs utils (Red Hat / CentOS)
    package:
      name: nfs-utils
    when: ansible_os_family == "RedHat"

- name: "Deploy NetApp Trident"
  hosts: kube-master
  become: false
  vars_files:
  - ../../config/group_vars/k8s-cluster.yml
  - ../../config/group_vars/netapp-trident.yml
  tasks:
  - name: Include netapp trident role
    run_once: true
    include_role:
      name: netapp-trident
      # apply:
      #   delegate_to: localhost
